"""empty message

Revision ID: 47255850e1c0
Revises: 3ee43bc19658
Create Date: 2025-08-13 22:50:50.365895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47255850e1c0'
down_revision = '3ee43bc19658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('personajeid',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planetid',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('planetid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('personajeid',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
